// Create T-shirt Order
export const CREATE_TSHIRT_ORDER_REQUEST = 'CREATE_TSHIRT_ORDER_REQUEST';
export const CREATE_TSHIRT_ORDER_SUCCESS = 'CREATE_TSHIRT_ORDER_SUCCESS';
export const CREATE_TSHIRT_ORDER_FAILURE = 'CREATE_TSHIRT_ORDER_FAILURE';

// Get T-shirt Orders
export const GET_TSHIRT_ORDERS_REQUEST = 'GET_TSHIRT_ORDERS_REQUEST';
export const GET_TSHIRT_ORDERS_SUCCESS = 'GET_TSHIRT_ORDERS_SUCCESS';
export const GET_TSHIRT_ORDERS_FAILURE = 'GET_TSHIRT_ORDERS_FAILURE'; 

export const UPDATE_TSHIRT_ORDER_REQUEST = 'UPDATE_TSHIRT_ORDER_REQUEST';
export const UPDATE_TSHIRT_ORDER_SUCCESS = 'UPDATE_TSHIRT_ORDER_SUCCESS';
export const UPDATE_TSHIRT_ORDER_FAILURE = 'UPDATE_TSHIRT_ORDER_FAILURE';

export const DELETE_TSHIRT_ORDER_REQUEST = 'DELETE_TSHIRT_ORDER_REQUEST';
export const DELETE_TSHIRT_ORDER_SUCCESS = 'DELETE_TSHIRT_ORDER_SUCCESS';
export const DELETE_TSHIRT_ORDER_FAILURE = 'DELETE_TSHIRT_ORDER_FAILURE'; 