// Create Edushop Category
export const CREATE_EDUSHOP_CATEGORY_REQUEST = 'CREATE_EDUSHOP_CATEGORY_REQUEST';
export const CREATE_EDUSHOP_CATEGORY_SUCCESS = 'CREATE_EDUSHOP_CATEGORY_SUCCESS';
export const CREATE_EDUSHOP_CATEGORY_FAILURE = 'CREATE_EDUSHOP_CATEGORY_FAILURE';

// Get Edushop Categories
export const GET_EDUSHOP_CATEGORIES_REQUEST = 'GET_EDUSHOP_CATEGORIES_REQUEST';
export const GET_EDUSHOP_CATEGORIES_SUCCESS = 'GET_EDUSHOP_CATEGORIES_SUCCESS';
export const GET_EDUSHOP_CATEGORIES_FAILURE = 'GET_EDUSHOP_CATEGORIES_FAILURE';

// Update Edushop Category
export const UPDATE_EDUSHOP_CATEGORY_REQUEST = 'UPDATE_EDUSHOP_CATEGORY_REQUEST';
export const UPDATE_EDUSHOP_CATEGORY_SUCCESS = 'UPDATE_EDUSHOP_CATEGORY_SUCCESS';
export const UPDATE_EDUSHOP_CATEGORY_FAILURE = 'UPDATE_EDUSHOP_CATEGORY_FAILURE';

// Delete Edushop Category
export const DELETE_EDUSHOP_CATEGORY_REQUEST = 'DELETE_EDUSHOP_CATEGORY_REQUEST';
export const DELETE_EDUSHOP_CATEGORY_SUCCESS = 'DELETE_EDUSHOP_CATEGORY_SUCCESS';
export const DELETE_EDUSHOP_CATEGORY_FAILURE = 'DELETE_EDUSHOP_CATEGORY_FAILURE'; 